/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Apr 14 2021 10:39:10 GMT-0500 (Central Daylight Time).
 */

define(['jointjs', 'css!./styles/AcoreWidget.css'], function (joint) {
    'use strict';

    var WIDGET_CLASS = 'sim-s-m';

    function AcoreWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this.nodes = {};
        this._initialize();

        this._logger.debug('ctor finished');
    }

    AcoreWidget.prototype._initialize = function () {
        // console.log(joint);
        var width = this._el.width(),
            height = this._el.height(),
            self = this;

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        this._jointSM = new joint.dia.Graph;
        this._jointPaper = new joint.dia.Paper({
            el: this._el,
            width : width,
            height: height,
            model: this._jointSM,
            interactive: false
        });

        // add event calls to elements
        this._jointPaper.on('element:pointerdblclick', function(elementView) {
            const currentElement = elementView.model;
            // console.log(currentElement);
            if (self._webgmeSM) {
                console.log(self._webgmeSM.id2state[currentElement.id]);
                self._setCurrentState(self._webgmeSM.id2state[currentElement.id]);
            }
        });

        this._webgmeSM = null;
    };

    AcoreWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    // State Machine manipulating functions called from the controller
    AcoreWidget.prototype.initMachine = function (machineDescriptor) {
        const self = this;
        // console.ßlog(machineDescriptor);

        self._webgmeSM = machineDescriptor;
        // console.log(self._webgmeSM)
        self._webgmeSM.current = self._webgmeSM.inplaces;
        // console.log(self._webgmeSM.current)
        self._jointSM.clear();
        const sm = self._webgmeSM;
        sm.id2state = {}; // this dictionary will connect the on-screen id to the state id
        // first add the states
        // console.log("Element keys are",Object.keys(sm.states));
        Object.keys(sm.states).forEach(stateId => {
            // console.log("IDs are: ",stateId);
            // console.log("states are: ",sm.states);
            // console.log("Transitions are:",sm.Transitions);
            // console.log("Arcs are",sm.Arcs);
            // console.log("Init is:",sm.init)
            // console.log("Inplaces are:",sm.inplaces)
            let vertex = null;
            // if (sm.init === stateId) {
            if (sm.inplaces.includes(stateId)){    
                vertex = new joint.shapes.standard.Circle({
                    position: sm.states[stateId].position,
                    size: { width: 40, height: 40 },
                    attrs: {
                        label : {text:sm.states[stateId].token,
                            fontWeight: 'bold',
                        },
                        body: {
                            fill: 'none',
                            cursor: 'pointer'
                        }
                    }
                });
            } else if (sm.states[stateId].isEnd) {
                vertex = new joint.shapes.standard.Circle({
                    position: sm.states[stateId].position,
                    size: { width: 30, height: 30 },
                    attrs: {
                        body: {
                            fill: '#999999',
                            cursor: 'pointer'
                        }
                    }
                });

            } else if (stateId in sm.Transitions){    
                vertex = new joint.shapes.standard.Rectangle({
                    position: sm.states[stateId].position,
                    size: { width: 80, height: 90 },
                    attrs: {
                        label : {text:sm.states[stateId].status,
                            fontWeight: 'bold',
                        },
                        body: {
                            fill: 'none',
                            cursor: 'pointer'
                        }
                    }
                });       
            } else {
                vertex = new joint.shapes.standard.Circle({
                    position: sm.states[stateId].position,
                    size: { width: 60, height: 60 },
                    attrs: {
                        label : {
                            text: sm.states[stateId].token,
                            //event: 'element:label:pointerdown',
                            fontWeight: 'bold',
                            //cursor: 'text',
                            //style: {
                            //    userSelect: 'text'
                            //}
                        },
                        body: {
                            strokeWidth: 3,
                            cursor: 'pointer'
                        }
                    }
                });
            }
            vertex.addTo(self._jointSM);
            sm.states[stateId].joint = vertex;
            sm.id2state[vertex.id] = stateId;
        });

        // then create the links
        // console.log(sm.Transitions)
        // console.log(sm.states)
        Object.keys(sm.states).forEach(stateId => {
            // console.log("Transitions are",sm.Transitions)
            const state = sm.states[stateId];
            // console.log("Each transition",state)
            Object.keys(state.next).forEach(event => {
                state.jointNext = state.jointNext || {};
                // console.log(event)
                // console.log(state.next[event])
                // console.log(sm.Transitions[state.next[event]])
                const link = new joint.shapes.standard.Link({
                    source: {id: state.joint.id},
                    target: {id: sm.states[state.next[event]].joint.id},
                    attrs: {
                        line: {
                            strokeWidth: 2
                        },
                        wrapper: {
                            cursor: 'default'
                        }
                    },
                    labels: [{
                        position: {
                            distance: 0.5,
                            offset: 0,
                            args: {
                                keepGradient: true,
                                ensureLegibility: true
                            }
                        },
                        attrs: {
                            text: {
                                text: event,
                                fontWeight: 'bold'
                            }
                        }
                    }]
                });
                link.addTo(self._jointSM);
                state.jointNext[event] = link;
                // console.log("...............",link,event,state)
            })
        });

        //now refresh the visualization
        self._jointPaper.updateViews();
        // console.log("This line is executed")
        self._decorateMachine();
        // console.log("This line is executed")
    };

    AcoreWidget.prototype.destroyMachine = function () {

    };

    AcoreWidget.prototype.fireEvent = function (event) {
        console.log("____________1");
        const self = this;
        self.aux_current = []
        console.log(self._webgmeSM.current)
        self._webgmeSM.current.forEach(ID =>{
            console.log("iteration num");
            const current = self._webgmeSM.states[ID];
            if (current.jointNext === undefined){console.log("if is being executed")
            } else {
                    console.log("else is being executed");
                    const link = current.jointNext[event];
                    const linkView = link.findView(self._jointPaper);
                    linkView.sendToken(joint.V('circle', { r: 10, fill: 'black' }), {duration:500}, function() {
                        // console.log(current.next[event]);
                        console.log(current.next[event]);
                        self.aux_current.push(current.next[event]);
                        // self._webgmeSM.current = current.next[event];
                        console.log(self.aux_current);
                        // self._decorateMachine();
                    });
                    console.log("what is this");
            }
            console.log("else got executed");
        });
        console.log("_______________________2")
        // console.log(self._webgmeSM.current)
        // self._webgmeSM.current = [];
        // self.aux_current.forEach(an => {self._webgmeSM.current.push(an)})
        self._webgmeSM.current = [...self.aux_current];
        console.log(self._webgmeSM.current)
        self._decorateMachine(self._webgmeSM.current);
        console.log("________________________________________3")

    };

    AcoreWidget.prototype.resetMachine = function () {
        console.log(this._webgmeSM)
        this._webgmeSM.current = this._webgmeSM.inplaces;
        this._decorateMachine();
    };

    AcoreWidget.prototype._decorateMachine = function() {
        // console.log(this._webgmeSM);
        const sm = this._webgmeSM;
        // console.log(this._webgmeSM.current)
        Object.keys(sm.states).forEach(stateId => {
            // console.log(sm.current)
            // console.log(stateId)
            sm.states[stateId].joint.attr('body/stroke', '#333333');
        });
        // console.log(sm.current)
        sm.current.forEach(initialnode => {sm.states[initialnode].joint.attr('body/stroke', 'blue');
        // console.log("___________________________",sm.states[initialnode].next)
        sm.setFireableEvents(Object.keys(sm.states[initialnode].next));})
        // sm.states[sm.current].joint.attr('body/stroke', 'blue');
        // sm.setFireableEvents(Object.keys(sm.states[sm.current].next));
    };

    AcoreWidget.prototype._setCurrentState = function(newCurrent) {
        this._webgmeSM.current = newCurrent;
        this._decorateMachine();
    };
    

    /* * * * * * * * Visualizer event handlers * * * * * * * */

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    AcoreWidget.prototype.destroy = function () {
    };

    AcoreWidget.prototype.onActivate = function () {
        this._logger.debug('AcoreWidget has been activated');
    };

    AcoreWidget.prototype.onDeactivate = function () {
        this._logger.debug('AcoreWidget has been deactivated');
    };

    return AcoreWidget;
});
