/*globals define, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Apr 14 2021 10:39:10 GMT-0500 (Central Daylight Time).
 */

define([
    'js/Constants',
    'js/Utils/GMEConcepts',
    'js/NodePropertyNames'
], function (
    CONSTANTS,
    GMEConcepts,
    nodePropertyNames
) {

    'use strict';

    function AcoreControl(options) {

        this._logger = options.logger.fork('Control');

        this._client = options.client;

        // Initialize core collections and variables
        this._widget = options.widget;

        this._currentNodeId = null;

        this._networkRootLoaded = false;

        this._fireableEvents = null;

        this._initWidgetEventHandlers();
        // console.log("Checking Fireable events:", this)

        // we need to fix the context of this function as it will be called from the widget directly
        this.setFireableEvents = this.setFireableEvents.bind(this);
        // console.log("check fireable events2 : ", this.setFireableEvents  )

        this._logger.debug('ctor finished');
    }

    AcoreControl.prototype._initWidgetEventHandlers = function () {
        this._widget.onNodeClick = function (id) {
            // Change the current active object
            WebGMEGlobal.State.registerActiveObject(id);
        };
    };

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    // One major concept here is with managing the territory. The territory
    // defines the parts of the project that the visualizer is interested in
    // (this allows the browser to then only load those relevant parts).
    AcoreControl.prototype.selectedObjectChanged = function (nodeId) {
        var desc = this._getObjectDescriptor(nodeId),
        self = this;

        self._logger.debug('activeObject nodeId \'' + nodeId + '\'');
        self._initialLoaded = true;

        // Remove current territory patterns
        if (self._currentNodeId) {
            self._client.removeUI(self._territoryId);
            self._networkRootLoaded = false;
        }

        self._currentNodeId = nodeId;
        self._currentNodeParentId = undefined;

        if (typeof self._currentNodeId === 'string') {
            // Put new node's info into territory rules
            self._selfPatterns = {};
            self._selfPatterns[nodeId] = {children: 1};  // Territory "rule"
            self._widget.setTitle(desc.name.toUpperCase());    
            self._territoryId = self._client.addUI(self, function (events) {
                self._eventCallback(events);
            });

            // Update the territory
            self._client.updateTerritory(self._territoryId, self._selfPatterns);
        }
    };

    AcoreControl.prototype._getObjectDescriptor = function (nodeId) {
        var node = this._client.getNode(nodeId),
            objDescriptor;
        if (node) {
            var metaId = node.getBaseTypeId();
            var metaNode = this._client.getNode(metaId);
            if (metaNode !== null) {
                var metaType = metaNode.getAttribute('name'); 
            } else {
                var metaType = null;
            }
            objDescriptor = {
                id: node.getId(),
                name: node.getAttribute(nodePropertyNames.Attributes.name),
                childrenIds: node.getChildrenIds(),
                parentId: node.getParentId(),
                isConnection: GMEConcepts.isConnection(nodeId),
                type: metaType 
            };
            if (objDescriptor.isConnection) {
                objDescriptor.src = node.getPointerId('src');
                objDescriptor.dst = node.getPointerId('dst');
            }
        }

        return objDescriptor;
    };

    /* * * * * * * * Node Event Handling * * * * * * * */
    AcoreControl.prototype._eventCallback = function (events) {
        const self = this;
        // console.log(events);
        events.forEach(event => {
            if (event.eid && 
                event.eid === self._currentNodeId ) {
                    if (event.etype == 'load' || event.etype == 'update') {
                        self._networkRootLoaded = true;
                    } else {
                        self.clearSM();
                        return;
                    }
                }
                
        });

        if (events.length && events[0].etype === 'complete' && self._networkRootLoaded) {
            // complete means we got all requested data and we do not have to wait for additional load cycles
            self._initSM();
        }
    };


    AcoreControl.prototype._stateActiveObjectChanged = function (model, activeObjectId) {
        if (this._currentNodeId === activeObjectId) {
            // The same node selected as before - do not trigger
        } else {
            this.selectedObjectChanged(activeObjectId);
        }
    };

    /* * * * * * * * Machine manipulation functions * * * * * * * */
    AcoreControl.prototype._initSM = function () {
        const self = this;
        //just for the ease of use, lets create a META dictionary
        const rawMETA = self._client.getAllMetaNodes();
        // console.log(self)
        const META = {};
        rawMETA.forEach(node => {
            META[node.getAttribute('name')] = node.getId();
 //we just need the id...
        });
        // console.log("............",META)
        //now we collect all data we need for network visualization
        //we need our states (names, position, type), need the set of next state (with event names)
        const smNode = self._client.getNode(self._currentNodeId);
        // console.log("######",smNode)
        const elementIds = smNode.getChildrenIds();
        // console.log(elementIds)
        const sm = {init:{ps:{},ts:{}}, states:{}, inarcs:{}, outarcs:{}, Transitions:{}};
        elementIds.forEach(elementId => {
            const node = self._client.getNode(elementId);
            // the simple way of checking type
            if (node.isTypeOf(META['Places'])) {
                //right now we only interested in states...
                const state = {name: node.getAttribute('name'), token: node.getAttribute('token'), next:{}, position: node.getRegistry('position'), setFireableEvents: null};
                // console.log('####',node)
                // console.log(state);
                // one way to check meta-type in the client context - though it does not check for generalization types like State
                // if ( === self._client.getNode(node.getMetaTypeId()).getAttribute('name')) {
                //     // sm.init = elementId;
                //     // sm.inplaces.push(elementId)
                //     sm.inplaces[elementId] = elementId;
                //     // console.log("............",sm)
                // }

                // this is in no way optimal, but shows clearly what we are looking for when we collect the data
                elementIds.forEach(nextId => {
                    const nextNode = self._client.getNode(nextId);
                    // console.log(nextId,"........",nextNode, elementId)
                    if(nextNode.isTypeOf(META['Arcs']) && nextNode.getPointerId('src') === elementId) {
                        // console.log(elementId,"connected to ",nextNode);
                        // console.log(nextNode.getAttribute('event'), '@@@@',nextNode.getPointerId('dst') )
                        state.next[nextNode.getPointerId('dst')] = nextNode.getPointerId('dst');
                    }
                });
                sm.states[elementId] = state;
                // console.log(sm);
            }

            if (node.isTypeOf(META['Transitions'])) {
                //right now we only interested in states...
                const transition = {name: node.getAttribute('name'), EN: null, next:{}, position: node.getRegistry('position'), inplaces:{}};
                // console.log(node.getAttribute('name'))
                // one way to check meta-type in the client context - though it does not check for generalization types like State
                // if ('Transitions' === self._client.getNode(node.getMetaTypeId()).getAttribute('name')) {
                //     sm.init = elementId;
                // }

                // this is in no way optimal, but shows clearly what we are looking for when we collect the data
                elementIds.forEach(nextId => {
                    const nextNode = self._client.getNode(nextId);
                    if(nextNode.isTypeOf(META['Arcs']) && nextNode.getPointerId('src') === elementId) {
                        // console.log(nextNode.getAttribute('event'),elementId)
                        transition.next[nextNode.getPointerId('dst')] = nextNode.getPointerId('dst');
                        // console.log("???????????",transition)
                    }
                });
                sm.Transitions[elementId] = transition;
                // sm.states[elementId] = transition;
            }
            // console.log(sm)
        });
        Object.keys(sm.states).forEach(stateID =>{
        	Object.keys(sm.states[stateID].next).forEach(tranID =>{
        		sm.Transitions[tranID].inplaces[stateID] = stateID;
        	});
        });
        sm.setFireableEvents = this.setFireableEvents;
        sm.init.ps = JSON.parse(JSON.stringify(sm.states));
        sm.init.ts = JSON.parse(JSON.stringify(sm.Transitions));
        self._widget.initMachine(sm);
    };

    AcoreControl.prototype.clearSM = function () {
        const self = this;
        self._networkRootLoaded = false;
        self._widget.destroyMachine();
    };

    AcoreControl.prototype.setFireableEvents = function (EVENTS) {
        this._fireableEvents = EVENTS;
        // console.log(EVENTS)
        if (EVENTS && Object.keys(EVENTS).length >= 1) {
            // we need to fill the dropdow button with options
            this.$btnEventSelector.clear();
            Object.keys(EVENTS).forEach(EVENT => {
            	// console.log(EVENT)
                this.$btnEventSelector.addButton({
                    text: EVENTS[EVENT],
                    title: 'fire event: '+ EVENTS[EVENT],
                    data: {EVENT: EVENT},
                    clickFn: data => {
                        this._widget.fireEvent(data.EVENT);
                    }
                });
            });
        } else if (EVENTS && Object.keys(EVENTS).length === 0) {
            this._fireableEvents = null;
            setTimeout(function(){
                window.alert("Deadlock Reached... Please Reset to continue...");
            }, 550); 
        }

        this._displayToolbarItems();
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    AcoreControl.prototype.destroy = function () {
        this._detachClientEventListeners();
        this._removeToolbarItems();
    };

    AcoreControl.prototype._attachClientEventListeners = function () {
        this._detachClientEventListeners();
        WebGMEGlobal.State.on('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged, this);
    };

    AcoreControl.prototype._detachClientEventListeners = function () {
        WebGMEGlobal.State.off('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged);
    };

    AcoreControl.prototype.onActivate = function () {
        this._attachClientEventListeners();
        this._displayToolbarItems();

        if (typeof this._currentNodeId === 'string') {
            WebGMEGlobal.State.registerActiveObject(this._currentNodeId, {suppressVisualizerFromNode: true});
        }
    };

    AcoreControl.prototype.onDeactivate = function () {
        this._detachClientEventListeners();
        this._hideToolbarItems();
    };

    /* * * * * * * * * * Updating the toolbar * * * * * * * * * */
    AcoreControl.prototype._displayToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].show();
            }
            if (this._fireableEvents === null) {
                this.$btnEventSelector.hide();
                this.$btnSingleEvent.hide();
            } else if (this._fireableEvents.length == 1) {
                this.$btnEventSelector.hide();
            } else {
                this.$btnSingleEvent.hide();
            }
        } else {
            this._initializeToolbar();
        }
    };

    AcoreControl.prototype._hideToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].hide();
            }
        }
    };

    AcoreControl.prototype._removeToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].destroy();
            }
        }
    };

    AcoreControl.prototype._initializeToolbar = function () {
        var self = this,
            toolBar = WebGMEGlobal.Toolbar;

        this._toolbarItems = [];

        this._toolbarItems.push(toolBar.addSeparator());

        /************** Go to hierarchical parent button ****************/
        this.$btnAcorePlugin = toolBar.addButton({
            title: 'Check state machine reachability properties',
            icon: 'glyphicon glyphicon-question-sign',
            clickFn: function (/*data*/) {
                const context = self._client.getCurrentPluginContext('AcorePlugin',self._currentNodeId, []);
                // !!! it is important to fill out or pass an empty object as the plugin config otherwise we might get errors...
                context.pluginConfig = {};
                self._client.runServerPlugin(
                    'AcorePlugin', 
                    context, 
                    function(err, result){
                        // here comes any additional processing of results or potential errors.
                        console.log('plugin err:', err);
                        console.log('plugin result:', result);
                });
            }
        });
        this._toolbarItems.push(this.$btnAcorePlugin);

        this.$btnResetMachine = toolBar.addButton({
            title: 'Reset simulator',
            icon: 'glyphicon glyphicon-fast-backward',
            clickFn: function (/*data*/) {
                self._widget.resetMachine();
            }
        });
        this._toolbarItems.push(this.$btnResetMachine);

        // when there are multiple events to choose from we offer a selector
        this.$btnEventSelector = toolBar.addDropDownButton({
            text: 'event'
        });
        this._toolbarItems.push(this.$btnEventSelector);
        this.$btnEventSelector.hide();

        // if there is only one event we just show a play button
        this.$btnSingleEvent = toolBar.addButton({
            title: 'Fire event',
            icon: 'glyphicon glyphicon-play',
            clickFn: function (/*data*/) {
                self._widget.fireEvent(self._fireableEvents[0]);
            }
        });
        this._toolbarItems.push(this.$btnSingleEvent);
        

        /************** Dropdown for event progression *******************/


        this._toolbarInitialized = true;
    };

    return AcoreControl;
});
